/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.20.0-SNAPSHOT).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.api;

import org.openapitools.model.ErrorResponse;
import org.openapitools.model.EventPollingRequestBody;
import org.openapitools.model.Response200ForEnrichEventPolling;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-02-13T04:23:17.978812429Z[Etc/UTC]", comments = "Generator version: 7.20.0-SNAPSHOT")
@Validated
@Tag(name = "Event Polling", description = "the Event Polling API")
public interface EnrichEventPollingResponseApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    String PATH_ENRICH_EVENT_POLLING_RESPONSE_POST = "/enrich-event-polling-response";
    /**
     * POST /enrich-event-polling-response : handle post event-polling response generation
     *
     * @param eventPollingRequestBody  (required)
     * @return Ok (status code 200)
     *         or Bad Request (status code 400)
     *         or Server Error (status code 500)
     */
    @Operation(
        operationId = "enrichEventPollingResponsePost",
        summary = "handle post event-polling response generation",
        tags = { "Event Polling" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Ok", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Response200ForEnrichEventPolling.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"responseId\":\"Ec1wMjmiG8\",\"status\":\"SUCCESS\",\"data\":{\"eventPollingResponse\":{}}}"
                    ),
                    @ExampleObject(
                        name = "",
                        value = "{\"status\":\"ERROR\",\"errorCode\":400,\"data\":{\"error\":\"Invalid Request\",\"errorMessage\":\"Invalid event polling payload\"}}"
                    )
                })

            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        },
        security = {
            @SecurityRequirement(name = "OAuth2"),
            @SecurityRequirement(name = "BasicAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = EnrichEventPollingResponseApi.PATH_ENRICH_EVENT_POLLING_RESPONSE_POST,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Response200ForEnrichEventPolling> enrichEventPollingResponsePost(
        @Parameter(name = "EventPollingRequestBody", description = "", required = true) @Valid @RequestBody EventPollingRequestBody eventPollingRequestBody
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"data\" : { \"eventPollingResponse\" : \"{}\" }, \"responseId\" : \"responseId\", \"status\" : \"SUCCESS\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"data\" : \"{}\", \"status\" : \"ERROR\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"data\" : \"{}\", \"status\" : \"ERROR\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
