/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.20.0-SNAPSHOT).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.api;

import org.openapitools.model.ErrorResponse;
import org.openapitools.model.PersistAuthorizedConsentRequestBody;
import org.openapitools.model.Response200ForPersistAuthorizedConsent;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-02-13T04:23:17.978812429Z[Etc/UTC]", comments = "Generator version: 7.20.0-SNAPSHOT")
@Validated
@Tag(name = "Consent", description = "APIs for consent flow extensions")
public interface PersistAuthorizedConsentApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    String PATH_PERSIST_AUTHORIZED_CONSENT_POST = "/persist-authorized-consent";
    /**
     * POST /persist-authorized-consent : handle consent persistence logic and enrich response with user authorization and account mapping data
     *
     * @param persistAuthorizedConsentRequestBody  (required)
     * @return Successful response (status code 200)
     *         or Bad Request (status code 400)
     *         or Server Error (status code 500)
     */
    @Operation(
        operationId = "persistAuthorizedConsentPost",
        summary = "handle consent persistence logic and enrich response with user authorization and account mapping data",
        tags = { "Consent" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Successful response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Response200ForPersistAuthorizedConsent.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        },
        security = {
            @SecurityRequirement(name = "OAuth2"),
            @SecurityRequirement(name = "BasicAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = PersistAuthorizedConsentApi.PATH_PERSIST_AUTHORIZED_CONSENT_POST,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Response200ForPersistAuthorizedConsent> persistAuthorizedConsentPost(
        @Parameter(name = "PersistAuthorizedConsentRequestBody", description = "", required = true) @Valid @RequestBody PersistAuthorizedConsentRequestBody persistAuthorizedConsentRequestBody
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"data\" : { \"consentResource\" : { \"validityTime\" : 0, \"authorizations\" : [ { \"resources\" : [ { \"accountId\" : \"accountId\", \"permission\" : \"permission\", \"status\" : \"status\" }, { \"accountId\" : \"accountId\", \"permission\" : \"permission\", \"status\" : \"status\" } ], \"type\" : \"type\", \"userId\" : \"userId\", \"status\" : \"status\" }, { \"resources\" : [ { \"accountId\" : \"accountId\", \"permission\" : \"permission\", \"status\" : \"status\" }, { \"accountId\" : \"accountId\", \"permission\" : \"permission\", \"status\" : \"status\" } ], \"type\" : \"type\", \"userId\" : \"userId\", \"status\" : \"status\" } ], \"recurringIndicator\" : true, \"receipt\" : \"{}\", \"attributes\" : \"{}\", \"type\" : \"type\", \"status\" : \"status\", \"frequency\" : 6 } }, \"responseId\" : \"responseId\", \"status\" : \"SUCCESS\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"data\" : \"{}\", \"status\" : \"ERROR\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"data\" : \"{}\", \"status\" : \"ERROR\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
