/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.20.0-SNAPSHOT).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.api;

import org.openapitools.model.CreateStandingOrderRequest;
import org.openapitools.model.ErrorResponse;
import org.openapitools.model.StandingOrderResponse;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-02-13T05:14:10.248730783Z[Etc/UTC]")
@Validated
@Tag(name = "Payment", description = "APIs for Payment Initiation Services (PIS) including standing orders")
public interface StandingOrdersApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    String PATH_STANDING_ORDERS_POST = "/standing-orders";
    String PATH_STANDING_ORDERS_GET = "/standing-orders/{standingOrderId}";

    /**
     * POST /standing-orders : Create a new standing order with structured additional information
     *
     * @param createStandingOrderRequest  (required)
     * @return Standing order created successfully (status code 201)
     *         or Bad Request (status code 400)
     *         or Server Error (status code 500)
     */
    @Operation(
        operationId = "standingOrdersPost",
        summary = "Create a new standing order with structured additional information",
        tags = { "Payment" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Standing order created successfully", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = StandingOrderResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        },
        security = {
            @SecurityRequirement(name = "OAuth2"),
            @SecurityRequirement(name = "BasicAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = StandingOrdersApi.PATH_STANDING_ORDERS_POST,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<StandingOrderResponse> standingOrdersPost(
        @Parameter(name = "CreateStandingOrderRequest", description = "", required = true) @Valid @RequestBody CreateStandingOrderRequest createStandingOrderRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"responseId\" : \"responseId\", \"standingOrderId\" : \"standingOrderId\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }

    /**
     * GET /standing-orders/{standingOrderId} : Retrieve a standing order by ID
     *
     * @param standingOrderId The unique identifier of the standing order (required)
     * @return Standing order retrieved successfully (status code 200)
     *         or Standing order not found (status code 404)
     *         or Server Error (status code 500)
     */
    @Operation(
        operationId = "standingOrdersStandingOrderIdGet",
        summary = "Retrieve a standing order by ID",
        tags = { "Payment" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Standing order retrieved successfully", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = StandingOrderResponse.class))
            }),
            @ApiResponse(responseCode = "404", description = "Standing order not found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        },
        security = {
            @SecurityRequirement(name = "OAuth2"),
            @SecurityRequirement(name = "BasicAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = StandingOrdersApi.PATH_STANDING_ORDERS_GET,
        produces = { "application/json" }
    )
    default ResponseEntity<StandingOrderResponse> standingOrdersStandingOrderIdGet(
        @Parameter(name = "standingOrderId", description = "The unique identifier of the standing order", required = true, in = ParameterIn.PATH) @PathVariable("standingOrderId") String standingOrderId
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"responseId\" : \"responseId\", \"standingOrderId\" : \"standingOrderId\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }
}
