/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.20.0-SNAPSHOT).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.api;

import org.openapitools.model.ErrorResponse;
import org.openapitools.model.Response200ForUpdatePaymentAuthorisation;
import org.openapitools.model.UpdatePaymentAuthorisationRequestBody;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.Optional;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-02-13T04:35:00.000000000Z[Etc/UTC]", comments = "Generator version: 7.20.0-SNAPSHOT")
@Validated
@Tag(name = "Payment", description = "APIs for payment authorization flow extensions")
public interface UpdatePaymentAuthorisationApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    String PATH_UPDATE_PAYMENT_AUTHORISATION = "/v1/{payment-service}/{paymentProduct}/{paymentId}/authorisations/{authorisationId}";
    
    /**
     * PUT /v1/{payment-service}/{paymentProduct}/{paymentId}/authorisations/{authorisationId} : Update payment initiation authorisation sub-resource data with authorization code
     *
     * @param paymentService Payment service (e.g., payments, bulk-payments, periodic-payments) (required)
     * @param paymentProduct Payment product (e.g., sepa-credit-transfers, instant-sepa-credit-transfers, target-2-payments, cross-border-credit-transfers) (required)
     * @param paymentId Resource identification of the generated payment initiation resource (required)
     * @param authorisationId Resource identification of the related SCA (required)
     * @param updatePaymentAuthorisationRequestBody  (required)
     * @return Successful response (status code 200)
     *         or Bad Request (status code 400)
     *         or Server Error (status code 500)
     */
    @Operation(
        operationId = "updatePaymentAuthorisation",
        summary = "Update payment initiation authorisation sub-resource data with authorization code",
        tags = { "Payment", "Authorize" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Successful response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Response200ForUpdatePaymentAuthorisation.class), examples = {
                    @ExampleObject(
                        name = "successExample",
                        value = "{\"responseId\":\"Ec1wMjmiG8\",\"status\":\"SUCCESS\",\"data\":{\"scaStatus\":\"finalised\",\"authorisationId\":\"123auth456\"}}"
                    ),
                    @ExampleObject(
                        name = "failedExample",
                        value = "{\"responseId\":\"Ec1wMjmiG8\",\"status\":\"ERROR\",\"errorCode\":401,\"errorMessage\":\"invalid_authentication\",\"errorDescription\":\"The authentication data provided is invalid\"}"
                    )
                })
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        },
        security = {
            @SecurityRequirement(name = "OAuth2"),
            @SecurityRequirement(name = "BasicAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = UpdatePaymentAuthorisationApi.PATH_UPDATE_PAYMENT_AUTHORISATION,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Response200ForUpdatePaymentAuthorisation> updatePaymentAuthorisation(
        @Parameter(name = "payment-service", description = "Payment service (e.g., payments, bulk-payments, periodic-payments)", required = true, in = ParameterIn.PATH) @PathVariable("payment-service") String paymentService,
        @Parameter(name = "paymentProduct", description = "Payment product (e.g., sepa-credit-transfers, instant-sepa-credit-transfers, target-2-payments, cross-border-credit-transfers)", required = true, in = ParameterIn.PATH) @PathVariable("paymentProduct") String paymentProduct,
        @Parameter(name = "paymentId", description = "Resource identification of the generated payment initiation resource", required = true, in = ParameterIn.PATH) @PathVariable("paymentId") String paymentId,
        @Parameter(name = "authorisationId", description = "Resource identification of the related SCA", required = true, in = ParameterIn.PATH) @PathVariable("authorisationId") String authorisationId,
        @Parameter(name = "UpdatePaymentAuthorisationRequestBody", description = "", required = true) @Valid @RequestBody UpdatePaymentAuthorisationRequestBody updatePaymentAuthorisationRequestBody
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"responseId\" : \"responseId\", \"status\" : \"SUCCESS\", \"data\" : { \"scaStatus\" : \"finalised\", \"authorisationId\" : \"123auth456\" } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }

}
