/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.20.0-SNAPSHOT).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.api;

import org.openapitools.model.ErrorResponse;
import org.openapitools.model.Response200ForPaymentCancellationAuthorization;
import org.openapitools.model.UpdatePaymentCancellationAuthorizationRequest;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.Optional;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-02-13T04:23:17.978812429Z[Etc/UTC]", comments = "Generator version: 7.20.0-SNAPSHOT")
@Validated
@Tag(name = "Payment Cancellation Authorization", description = "APIs for payment cancellation authorization extensions")
public interface UpdatePaymentCancellationAuthorizationApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * PUT /v1/{payment-service}/{payment-product}/{paymentId}/cancellationauthorisations/{authorisationId} : Update payment cancellation authorization
     * Updates payment initiation cancellation authorization sub-resource data with an authorization code
     *
     * @param paymentService Payment service (e.g., payments, bulk-payments, periodic-payments) (required)
     * @param paymentProduct Payment product identifier (e.g., sepa-credit-transfers) (required)
     * @param paymentId Payment identifier (required)
     * @param authorisationId Cancellation authorization identifier (required)
     * @param updatePaymentCancellationAuthorizationRequest  (required)
     * @return Successful response (status code 200)
     *         or Bad Request (status code 400)
     *         or Server Error (status code 500)
     */
    @Operation(
        operationId = "updatePaymentCancellationAuthorization",
        summary = "Update payment cancellation authorization",
        description = "Updates payment initiation cancellation authorization sub-resource data with an authorization code",
        tags = { "Payment Cancellation Authorization" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Successful response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Response200ForPaymentCancellationAuthorization.class), examples = {
                    @ExampleObject(
                        name = "Success",
                        value = "{\"responseId\":\"Ec1wMjmiG8\",\"status\":\"SUCCESS\",\"data\":{\"scaStatus\":\"finalised\",\"authorisationId\":\"auth123\"}}"
                    ),
                    @ExampleObject(
                        name = "Error",
                        value = "{\"responseId\":\"Ec1wMjmiG8\",\"status\":\"ERROR\",\"errorCode\":401,\"errorMessage\":\"invalid_authorization_code\",\"errorDescription\":\"The provided authorization code is invalid\"}"
                    )
                })
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        },
        security = {
            @SecurityRequirement(name = "BasicAuth"),
            @SecurityRequirement(name = "OAuth2")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/v1/{payment-service}/{payment-product}/{paymentId}/cancellationauthorisations/{authorisationId}",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Response200ForPaymentCancellationAuthorization> updatePaymentCancellationAuthorization(
        @Parameter(name = "payment-service", description = "Payment service (e.g., payments, bulk-payments, periodic-payments)", required = true, in = ParameterIn.PATH) @PathVariable("payment-service") String paymentService,
        @Parameter(name = "payment-product", description = "Payment product identifier (e.g., sepa-credit-transfers)", required = true, in = ParameterIn.PATH) @PathVariable("payment-product") String paymentProduct,
        @Parameter(name = "paymentId", description = "Payment identifier", required = true, in = ParameterIn.PATH) @PathVariable("paymentId") String paymentId,
        @Parameter(name = "authorisationId", description = "Cancellation authorization identifier", required = true, in = ParameterIn.PATH) @PathVariable("authorisationId") String authorisationId,
        @Parameter(name = "UpdatePaymentCancellationAuthorizationRequest", description = "", required = true) @Valid @RequestBody UpdatePaymentCancellationAuthorizationRequest updatePaymentCancellationAuthorizationRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"responseId\" : \"responseId\", \"data\" : { \"scaStatus\" : \"scaStatus\", \"authorisationId\" : \"authorisationId\", \"psuMessage\" : \"psuMessage\" }, \"errorCode\" : 0, \"errorMessage\" : \"errorMessage\", \"status\" : \"SUCCESS\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }

}
